// src/config/domain.ts — ПОЛНАЯ ЗАМЕНА

export const LANGUAGE_PAIRS = ['EN↔RU', 'EN↔ES'];

export const CONTEXTS = [
  { id: 'law', ru: 'Право', en: 'Law' },
  { id: 'travel', ru: 'Туризм', en: 'Travel' },
  { id: 'it', ru: 'IT', en: 'IT' },
  { id: 'senior', ru: '60+', en: '60+' },
];

export const STYLES = [
  { id: 'simple', ru: 'Простой', en: 'Simple' },
  { id: 'professional', ru: 'Профессиональный', en: 'Professional' },
  { id: 'academic', ru: 'Академический', en: 'Academic' },
];

export const HORIZONS = [
  { days: 30, ru: '30 дней', en: '30 days' },
  { days: 60, ru: '60 дней', en: '60 days' },
  { days: 90, ru: '90 дней', en: '90 days' },
];

// Базовые списки слов по контекстам — нужно для формирования пакета слов
export const HEADWORD_SEED: Record<string, string[]> = {
  law: [
    'court',
    'lawyer',
    'judge',
    'trial',
    'plaintiff',
    'defendant',
    'evidence',
    'witness',
    'verdict',
    'appeal',
    'sentence',
    'prosecutor',
    'crime',
    'case',
    'arrest',
    'contract',
    'agreement',
    'fine',
    'rights',
    'law',
    'claim',
    'hearing',
    'jury',
    'justice',
    'complaint',
    'police',
    'investigation',
    'testimony',
    'petition',
    'bail',
  ],
  travel: [
    'airport',
    'flight',
    'ticket',
    'boarding',
    'luggage',
    'passport',
    'visa',
    'reservation',
    'hotel',
    'check-in',
    'check-out',
    'breakfast',
    'taxi',
    'bus',
    'train',
    'platform',
    'seat',
    'gate',
    'delayed',
    'tour',
    'map',
    'museum',
    'beach',
    'restaurant',
    'bill',
    'tip',
    'tourist',
    'guide',
    'embassy',
    'insurance',
  ],
  it: [
    'computer',
    'software',
    'hardware',
    'server',
    'client',
    'database',
    'query',
    'API',
    'frontend',
    'backend',
    'bug',
    'feature',
    'deploy',
    'cloud',
    'account',
    'login',
    'password',
    'update',
    'version',
    'repository',
    'commit',
    'branch',
    'merge',
    'issue',
    'ticket',
    'sprint',
    'agile',
    'test',
    'build',
    'release',
  ],
  senior: [
    'appointment',
    'clinic',
    'doctor',
    'nurse',
    'medicine',
    'prescription',
    'pharmacy',
    'blood pressure',
    'insurance',
    'policy',
    'benefits',
    'pension',
    'retirement',
    'hearing aid',
    'glasses',
    'transport',
    'discount',
    'ID',
    'form',
    'office',
    'queue',
    'schedule',
    'checkup',
    'emergency',
    'hospital',
    'home care',
    'social services',
    'family',
    'neighbour',
  ],
};
// Рекомендации "слов в день" по горизонту — базовые значения
export const RECO_BASE_BY_DAYS: Record<
  number,
  { min: number; max: number; suggested: number }
> = {
  30: { min: 6, max: 10, suggested: 8 },
  60: { min: 5, max: 9, suggested: 7 },
  90: { min: 4, max: 8, suggested: 6 },
};
